name: 'transit'
version: '1.0.0'

# set "profile" dbt uses for project
profile: postgres

# disable usage stats
# documentation: https://docs.getdbt.com/reference/global-configs/usage-stats
flags:
  send_anonymous_usage_stats: false

# specify where dbt should look for different types of files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:
  - 'target'
  - 'dbt_packages'

# ===== variable configs =====
vars:

  infinity_future: to_date('9999-12-31', 'YYYY-MM-DD')
  infinity_past: to_date('1970-01-01', 'YYYY-MM-DD')
  tomorrow: dateadd('day', 1, current_date())
  sample_suffix: __sample
  local_data: sample
  dev_db_object_expiration: -80

  valid_at: '{{ run_started_at.strftime("%Y-%m-%d %H:%M:%S%z") }}'

  dbt_utils:
    surrogate_key_treat_nulls_as_empty_strings: True

# ===== model configs =====
# documentation: https://docs.getdbt.com/docs/configuring-models
models:

  transit:

    example:
      +materialized: view
      +schema: example
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
