postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: dev
      schema: dbt
      threads: 1
      connect_timeout: 10
      retries: 1
    prod:
      type: postgres
      host: localhost
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: prod
      schema: dbt
      threads: 1
      connect_timeout: 10
      retries: 1
