name: Copy labels from linked issues
on:
  pull_request:
    types: [opened, edited, review_requested, synchronize, reopened, ready_for_review]

permissions:
  issues: read
  contents: read
  pull-requests: write

jobs:
  inherit-issue-labels:
    runs-on: ubuntu-latest
    steps:
      # - name: inherit-issue-labels
      - uses: michalvankodev/copy-issue-labels@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels-to-exclude: |
            untriaged
            triaged
